#include "Trajectory.hpp"

#include <Eigen/Core>
#include <Eigen/Geometry>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

namespace fs = std::filesystem;
using visualsim::ForwardConstantVelocity;
using visualsim::OpticalAxisConstantRotation;
using visualsim::Pose;
using visualsim::Trajectory;

namespace {

struct CameraConfig {
  int width = 752;
  int height = 480;
  double fx = 458.654;
  double fy = 457.296;
  double cx = 367.215;
  double cy = 248.375;
  double rate_hz = 20.0;
};

std::vector<Eigen::Vector3d> MakeLandmarks() {
  std::vector<Eigen::Vector3d> pts;
  pts.reserve(1200);

  // Three textured planes in front of the camera. The asymmetry avoids
  // accidental rotational symmetry in the generated images.
  for (int ix = -10; ix <= 10; ++ix) {
    for (int iy = -7; iy <= 7; ++iy) {
      pts.emplace_back(0.35 * ix, 0.35 * iy, 6.0);
      if ((ix + 2 * iy) % 2 == 0)
        pts.emplace_back(0.28 * ix + 0.15, 0.30 * iy - 0.10, 9.0);
      if ((2 * ix - iy) % 3 == 0)
        pts.emplace_back(0.25 * ix - 0.20, 0.24 * iy + 0.18, 12.0);
    }
  }
  return pts;
}

cv::Mat Render(const CameraConfig& c, const Pose& pose,
               const std::vector<Eigen::Vector3d>& landmarks_w) {
  cv::Mat image(c.height, c.width, CV_8UC1, cv::Scalar(18));
  const Eigen::Matrix3d R_cw = pose.R_wc.transpose();

  for (std::size_t i = 0; i < landmarks_w.size(); ++i) {
    const Eigen::Vector3d p_c = R_cw * (landmarks_w[i] - pose.position_w);
    if (p_c.z() <= 0.15)
      continue;

    const double u = c.fx * p_c.x() / p_c.z() + c.cx;
    const double v = c.fy * p_c.y() / p_c.z() + c.cy;
    if (u < 4 || u >= c.width - 4 || v < 4 || v >= c.height - 4)
      continue;

    const int intensity = 70 + static_cast<int>((37 * i) % 170);
    const int radius = 1 + static_cast<int>(i % 3);
    cv::circle(image, cv::Point(cvRound(u), cvRound(v)), radius,
               cv::Scalar(intensity), cv::FILLED, cv::LINE_AA);
    if (i % 5 == 0) {
      cv::line(image, cv::Point(cvRound(u) - 2, cvRound(v)),
               cv::Point(cvRound(u) + 2, cvRound(v)),
               cv::Scalar(std::min(255, intensity + 25)), 1, cv::LINE_AA);
    }
  }

  return image;
}

void WriteSensorYaml(const fs::path& path, const CameraConfig& c) {
  std::ofstream out(path);
  if (!out)
    throw std::runtime_error("cannot write sensor.yaml");

  out << "sensor_type: camera\n";
  out << "comment: generated by ncut-d1z/VisualSim\n";
  out << "T_BS:\n";
  out << "  rows: 4\n  cols: 4\n";
  out << "  data: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]\n";
  out << "rate_hz: " << c.rate_hz << "\n";
  out << "resolution: [" << c.width << ", " << c.height << "]\n";
  out << std::setprecision(12);
  out << "camera_model: pinhole\n";
  out << "intrinsics: [" << c.fx << ", " << c.fy << ", " << c.cx << ", "
      << c.cy << "]\n";
  out << "distortion_model: radial-tangential\n";
  out << "distortion_coefficients: [0, 0, 0, 0]\n";
}

void WriteGroundTruthHeader(std::ofstream& out) {
  out << "#timestamp [ns],p_RS_R_x [m],p_RS_R_y [m],p_RS_R_z [m],"
         "q_RS_w [],q_RS_x [],q_RS_y [],q_RS_z [],"
         "v_RS_R_x [m s^-1],v_RS_R_y [m s^-1],v_RS_R_z [m s^-1],"
         "a_RS_R_x [m s^-2],a_RS_R_y [m s^-2],a_RS_R_z [m s^-2],"
         "w_RS_S_x [rad s^-1],w_RS_S_y [rad s^-1],w_RS_S_z [rad s^-1]\n";
}

void GenerateDataset(const fs::path& output_root, const Trajectory& trajectory,
                     const CameraConfig& camera) {
  const fs::path root = output_root / trajectory.name() / "mav0";
  const fs::path cam0 = root / "cam0";
  const fs::path image_dir = cam0 / "data";
  const fs::path gt_dir = root / "state_groundtruth_estimate0";

  fs::remove_all(root.parent_path());
  fs::create_directories(image_dir);
  fs::create_directories(gt_dir);

  WriteSensorYaml(cam0 / "sensor.yaml", camera);

  std::ofstream cam_csv(cam0 / "data.csv");
  std::ofstream gt_csv(gt_dir / "data.csv");
  std::ofstream meta(root / "README.txt");
  if (!cam_csv || !gt_csv || !meta)
    throw std::runtime_error("cannot create dataset output files");

  cam_csv << "#timestamp [ns],filename\n";
  WriteGroundTruthHeader(gt_csv);

  meta << "scenario: " << trajectory.name() << "\n";
  meta << "duration_s: " << trajectory.duration() << "\n";
  meta << "camera_rate_hz: " << camera.rate_hz << "\n";
  meta << "camera_forward_axis: +Z\n";
  meta << "camera_frame: +X right, +Y down, +Z forward\n";

  const auto landmarks = MakeLandmarks();
  const double dt = 1.0 / camera.rate_hz;
  const std::size_t frame_count =
      static_cast<std::size_t>(std::floor(trajectory.duration() / dt)) + 1;

  for (std::size_t k = 0; k < frame_count; ++k) {
    const double t = std::min(trajectory.duration(), k * dt);
    const std::int64_t timestamp_ns =
        static_cast<std::int64_t>(std::llround(t * 1e9));

    const Pose pose = trajectory.pose(t);
    const auto kin = trajectory.kinematics(t);
    const Eigen::Quaterniond q_wc(pose.R_wc);

    const std::string filename = std::to_string(timestamp_ns) + ".png";
    const cv::Mat image = Render(camera, pose, landmarks);
    if (!cv::imwrite((image_dir / filename).string(), image))
      throw std::runtime_error("failed to write image");

    cam_csv << timestamp_ns << "," << filename << "\n";
    gt_csv << std::setprecision(17) << timestamp_ns << ","
           << pose.position_w.x() << "," << pose.position_w.y() << ","
           << pose.position_w.z() << "," << q_wc.w() << "," << q_wc.x()
           << "," << q_wc.y() << "," << q_wc.z() << ","
           << kin.velocity_w.x() << "," << kin.velocity_w.y() << ","
           << kin.velocity_w.z() << "," << kin.acceleration_w.x() << ","
           << kin.acceleration_w.y() << "," << kin.acceleration_w.z() << ","
           << kin.angular_velocity_c.x() << ","
           << kin.angular_velocity_c.y() << ","
           << kin.angular_velocity_c.z() << "\n";
  }
}

}  // namespace

int main(int argc, char** argv) {
  try {
    const fs::path output_root = argc > 1 ? fs::path(argv[1]) : fs::path("datasets");
    CameraConfig camera;

    // Scenario 1:
    // R_wc(t) = I,
    // p_w(t) = [0, 0, v t]^T.
    ForwardConstantVelocity forward(
        /*duration_s=*/8.0,
        /*speed_mps=*/0.25,
        Eigen::Vector3d(0.0, 0.0, 0.0),
        Eigen::Matrix3d::Identity());

    // Scenario 2:
    // p_w(t) = constant,
    // R_wc(t) = Exp(e_z * omega * t), i.e. constant roll around optical axis.
    OpticalAxisConstantRotation rotation(
        /*duration_s=*/8.0,
        /*omega_rad_s=*/0.35,
        Eigen::Vector3d(0.0, 0.0, 0.0),
        Eigen::Matrix3d::Identity());

    GenerateDataset(output_root, forward, camera);
    GenerateDataset(output_root, rotation, camera);

    std::cout << "Generated:\n  "
              << fs::absolute(output_root / forward.name()) << "\n  "
              << fs::absolute(output_root / rotation.name()) << "\n";
    return 0;
  } catch (const std::exception& e) {
    std::cerr << "VisualSim error: " << e.what() << "\n";
    return 1;
  }
}
